### ISSUE TITLE
UIX project is missing files in a Debug folder

### ISSUE THREAD

**Issue by user004918495** [ZuneDev/ZuneShell.dll#1]
The UIX.csproj file references some files, but they are not in the GIT repo. I'm guessing the ignores file decided not to include the folder because it normally ignores DEBUG and RELEASE folders, but in this case, it contains some decompiled files.

From the UIX.csproj:

    <Compile Include="Microsoft\Iris\Debug\Assert.cs" />

    <Compile Include="Microsoft\Iris\Debug\DebugHelpers.cs" />

    <Compile Include="Microsoft\Iris\Debug\DebugOutlineScope.cs" />

    <Compile Include="Microsoft\Iris\Debug\DebugLabelFormat.cs" />

    <Compile Include="Microsoft\Iris\Debug\DebugOutlines.cs" />

    <Compile Include="Microsoft\Iris\Debug\Trace.cs" />

    <Compile Include="Microsoft\Iris\Debug\RendererDebugCategory.cs" />

    <Compile Include="Microsoft\Iris\Debug\TraceCategory.cs" />

    <Compile Include="Microsoft\Iris\Debug\TraceSettings.cs" />

    <Compile Include="Microsoft\Iris\Debug\RegistryKey.cs" />

**Comment by yoshiask** [comment]
Whoops, forgot to close this! The files should be included in the repo now :)
